CREATE TABLE IF NOT EXISTS PLAYERKITS_PLAYERS(
	UUID VARCHAR(200) PRIMARY KEY,
	PLAYER_NAME VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS PLAYERKITS_PLAYERS_KITS (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	UUID VARCHAR(200) NOT NULL,
	NAME VARCHAR(100),
	COOLDOWN BIGINT,
	ONE_TIME BOOLEAN,
	BOUGHT BOOLEAN,
		FOREIGN KEY (UUID) REFERENCES PLAYERKITS_PLAYERS(UUID) ON DELETE CASCADE
);
